### ISSUE TITLE
Checksums

### ISSUE THREAD

**Issue by Erquint** [sayucchin/P2-EP-PSP#13]
The documentation should disclose checksums for the file to be patched as well as the resulting file to let the user double-check they're working with the right data.
These are the checksums I'm observing at f61f75b60968f3dad47fc77983d51f99034f2858:
### Subject
```
CRC-32: e149b113
   MD4: 31bf93dc426b7faad81089c185b7fa1a
   MD5: 6ceaa7572c4619d763ba953f8ec78fa9
 SHA-1: c7df3598b72e293ad5a338e54df2e8fecde8e616
```
### Result
```
CRC-32: fcd1ca15
   MD4: 895b25ee10387bfa41cebcc0463254e5
   MD5: 437f9754f72c3c15f149bd750ed9e1cd
 SHA-1: d63b18a71c872fb1a6a89cdd90d56ae2a8b2c155
```
The result checksums are subject to change and to be updated in case of alterations to the patch.

**Comment by sayucchin** [comment]
The checksums depend on what ISO you patched. So it won't be the same for everyone.

**Comment by Erquint** [comment]
First of all, that's why I include the checksums of the subject file.
People wanna be able to check if the patch will work with the file they got.
Secondly, if your patch is applicable to other files, I will again urge you to provide checksums of such for the users to have any idea if they're working with the right data on hand.

**Comment by eiowlta** [comment]
So we know there are at least two different sha1sums of the original ISO depending on where it came from, but without samples from more people, we can't say for certain how many there are.
The patcher itself doesn't check any checksums internally.  It also does not modify the original data at all, rather it produces a new ISO.
We did originally have the checksum you mentioned, but it was confusing to others because it did not match their checksum.  
The correct data to have is a copy of the (or rather a) japanese PSP ISO.  I feel this is quite clear from the instructions.
